language: go
go:
  - "1.11.x"
- 1.11.x
- tip

env:
  # deps are vendored
  GO111MODULE: 'off'

script:
- make test
- make vet
- make website-test

matrix:
  fast_finish: true
  allow_failures:
  - go: 1.11.x
  - go: tip
