name: Compiling

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Compile on all supported OSes
  compile:
    strategy:
      matrix:
        go-version:
           - 1.13.x
           - 1.14.x
           - 1.15.x
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Compile
      run: make compile-only

